name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use mode 16.11
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.0
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm run test:unit
